# resolve-file-bridge installer (Windows). Usually started via install.bat.
#   -Uninstall     remove the Scripts-menu launcher and the RESOLVE_BRIDGE_ROOT variable
#   -SkipMcp       don't offer to install the Python 'mcp' package
param([switch]$Uninstall, [switch]$SkipMcp)
$ErrorActionPreference = "Stop"

$Root      = (Resolve-Path $PSScriptRoot).Path.TrimEnd('\') + '\'
$ScriptDir = Join-Path $env:APPDATA "Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility"
$Launcher  = Join-Path $ScriptDir "Resolve Bridge Listen.lua"
$Utf8NoBom = New-Object System.Text.UTF8Encoding $false   # Lua chokes on a BOM

if ($Uninstall) {
    if (Test-Path $Launcher) { Remove-Item $Launcher; Write-Host "Removed $Launcher" }
    [Environment]::SetEnvironmentVariable("RESOLVE_BRIDGE_ROOT", $null, "User")
    Write-Host "Removed RESOLVE_BRIDGE_ROOT. The bridge folder itself was left in place."
    exit 0
}

Write-Host "resolve-file-bridge installer"
Write-Host "  bridge folder : $Root"
if ($Root -match '[^\x00-\x7F]') {
    Write-Warning "The folder path contains non-ASCII characters. Resolve's Lua may not open it - prefer e.g. C:\resolve-file-bridge"
}
if ($Root -match 'OneDrive|Dropbox|Google Drive') {
    Write-Warning "The folder looks cloud-synced. Anything written to its inbox runs inside Resolve - keep it local (see SECURITY.md)."
}

# 1. runtime folders
foreach ($d in "inbox", "outbox", "archive", "renders") { New-Item -ItemType Directory -Force -Path (Join-Path $Root $d) | Out-Null }

# 2. launcher in Resolve's Scripts menu
New-Item -ItemType Directory -Force -Path $ScriptDir | Out-Null
$lua = @"
-- resolve-file-bridge launcher (generated by install.ps1 - re-run the installer if you move the bridge folder)
local ROOT = [[$Root]]
dofile(ROOT .. [[resolve\resolve_bridge.lua]])({
  root    = ROOT,
  minutes = 0,          -- 0 = listen until stopped (client/bridge.py stop)
  carrier = "auto",     -- "comp" = old behaviour (renames the open comp)
})
"@
[IO.File]::WriteAllText($Launcher, $lua, $Utf8NoBom)
Write-Host "  launcher      : $Launcher"

# 3. environment variable for the client / MCP server
[Environment]::SetEnvironmentVariable("RESOLVE_BRIDGE_ROOT", $Root, "User")
Write-Host "  RESOLVE_BRIDGE_ROOT set for your user (new terminals will see it)"

# 4. optional: mcp package
$py = Get-Command python -ErrorAction SilentlyContinue
if (-not $py) { $py = Get-Command py -ErrorAction SilentlyContinue }
if ($py -and -not $SkipMcp) {
    $ans = Read-Host "Install the Python 'mcp' package for the MCP server? [y/N]"
    if ($ans -match '^[yY]') { & $py.Source -m pip install --user mcp }
} elseif (-not $py) {
    Write-Host "  (Python not found - the Lua side works without it; bridge.py / mcp_server.py need Python 3.9+)"
}

# 5. next steps
$server = (Join-Path $Root "client\mcp_server.py") -replace '\\', '\\'
$rootJ  = $Root -replace '\\', '\\'
Write-Host ""
Write-Host "Done. Next:"
Write-Host "  1. Restart DaVinci Resolve, open a project."
Write-Host "  2. Workspace > Scripts > Resolve Bridge Listen   (Workspace > Console shows 'listening on ...')"
Write-Host "  3. Test in a NEW terminal:  python `"$($Root)client\bridge.py`" ping"
Write-Host ""
Write-Host "MCP client config (Claude Desktop / Claude Code):"
Write-Host "  { `"mcpServers`": { `"resolve`": { `"command`": `"python`", `"args`": [`"$server`"],"
Write-Host "      `"env`": { `"RESOLVE_BRIDGE_ROOT`": `"$rootJ`" } } } }"
