#!/usr/bin/env bash
# resolve-file-bridge installer for macOS / Linux.   ./install.sh   |   ./install.sh --uninstall
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/"
case "$(uname -s)" in
  Darwin) SCRIPT_DIR="$HOME/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility" ;;
  *)      SCRIPT_DIR="$HOME/.local/share/DaVinciResolve/Fusion/Scripts/Utility" ;;
esac
LAUNCHER="$SCRIPT_DIR/Resolve Bridge Listen.lua"

if [[ "${1:-}" == "--uninstall" ]]; then
  rm -f "$LAUNCHER" && echo "Removed $LAUNCHER"
  echo "Remove the RESOLVE_BRIDGE_ROOT line from your shell profile if you added it."
  exit 0
fi

echo "resolve-file-bridge installer"
echo "  bridge folder : $ROOT"
mkdir -p "$ROOT"{inbox,outbox,archive,renders}
mkdir -p "$SCRIPT_DIR"
cat > "$LAUNCHER" <<LUA
-- resolve-file-bridge launcher (generated by install.sh - re-run it if you move the bridge folder)
local ROOT = [[$ROOT]]
dofile(ROOT .. "resolve/resolve_bridge.lua")({
  root    = ROOT,
  minutes = 0,          -- 0 = listen until stopped (client/bridge.py stop)
  carrier = "auto",     -- "comp" = old behaviour (renames the open comp)
})
LUA
echo "  launcher      : $LAUNCHER"
echo
echo "Done. Next:"
echo "  1. Add to your shell profile:  export RESOLVE_BRIDGE_ROOT=\"$ROOT\""
echo "  2. Restart DaVinci Resolve, open a project, Workspace > Scripts > Resolve Bridge Listen"
echo "  3. Test:  python3 \"${ROOT}client/bridge.py\" --root \"$ROOT\" ping"
echo "  Optional MCP server:  pip install mcp   then point your MCP client at ${ROOT}client/mcp_server.py"
